### PR TITLE
[WIP] Initial Commit

### PR DESCRIPTION
**Pull request by mvriel**
In this commit I deliver a framework to do asynchronous communication of
commands using tactician. This framework is based on the existing production
code and changed to be more flexible and to seggregate responsibilities
a little more.

Due to time constraints I had to wait with writing all the tests and there
may be a bug here or there.

### CODE REVIEW

**Comment by JerryVerhoef** [comment]
👍

**Comment by JerryVerhoef** [comment]
rename repo to async middleware and move to gitlab!

**Comment by mvriel** [comment]
Moved to https://gitlab.com/psybizz/tactician-rabbitmq-middleware

**Comment by mvriel** [comment]
https://gitlab.com/psybizz/tactician-rabbitmq-middleware/merge_requests

**Pull request closed without merging**
